development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: movies_production
